name: intl_phone_number_countries
description: package flutter to handle phone masks from other countries.
version: 1.0.0
homepage: https://github.com/nrbedin/intl_phone_number_countries

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dlibphonenumber: ^1.1.17
  equatable: ^2.0.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/flags/
